site_name: hal.guru
site_url: https://docs.hal.guru/
site_author: hal.guru
site_description: >-
  AI Robots thats works, for you
repo_name: hal-guru/hal.guru
repo_url: https://github.com/HAL-guru/hal.guru.git
nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'AI robot tutorial': 'ai-robot-tutorial.md'
  - About:
    - 'License': 'license.md'
theme: material
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"